''' Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. '''

import time

start = time.time()

summ = 2
i = 2
prev = 1

while (i < 4000000):
	i = i + prev
	prev = i - prev

	if (i % 2 == 0):
		summ += i

print(summ)

print("Operation took " + str(time.time() - start) + " seconds")


'''
> python3 problem2.py
4613732
Operation took 0.012999296188354492 seconds

'''